project:
  type: website
  output-dir: docs

website:
  title: "My Quarto Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: introduction.qmd
        text: Introducción
      - text: Análisis
        menu:
        - href: univariate.qmd
          text: Análisis Univariado
        - href: bivariate.qmd
          text: Análisis Bivariado

format:
  html:
    theme: cosmo
    toc: true